# Generated by Django 4.2.4 on 2023-10-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_book_details_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_book_details',
            name='stock_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
