# Generated by Django 4.2.4 on 2023-10-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_student_book_details_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_add_book',
            name='Quantity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
