# Generated by Django 4.2 on 2025-03-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_booked_concert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked_concert',
            name='available_tickets',
        ),
    ]
