# Generated by Django 4.2 on 2025-03-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_booked_concert_available_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_concert',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='concert',
            name='available_tickets',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
