# Generated by Django 4.1 on 2025-03-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_concert_available_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked_concert',
            name='ticket_no',
            field=models.CharField(max_length=10),
        ),
    ]
