# Generated by Django 4.2.11 on 2026-05-15 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0002_add_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
