# Generated by Django 4.2.11 on 2026-05-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='changes',
            new_name='new_values',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
