# Generated by Django 5.1.1 on 2025-03-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concert_name', models.CharField(max_length=100)),
                ('concert_date', models.DateField()),
                ('concert_time', models.TimeField()),
                ('concert_location', models.CharField(max_length=100)),
                ('available_tickets', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
