# Generated by Django 4.2 on 2025-03-15 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_concert_concert_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booked_concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(max_length=10, unique=True)),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('concert_name', models.CharField(max_length=100)),
                ('concert_date', models.DateField()),
                ('concert_time', models.CharField(max_length=250)),
                ('concert_location', models.CharField(max_length=100)),
                ('available_tickets', models.DecimalField(decimal_places=0, max_digits=10)),
                ('prize', models.DecimalField(decimal_places=2, max_digits=10)),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.concert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
