# Generated by Django 4.1 on 2025-03-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_booked_concert_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='available_tickets',
            field=models.CharField(max_length=100),
        ),
    ]
