# Generated by Django 4.2 on 2025-05-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_booked_concert_ticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='status',
            field=models.CharField(default='Disable', max_length=50),
        ),
    ]
