# Generated by Django 4.2.4 on 2023-10-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_admin_add_book_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_add_book',
            name='Quantity',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
