# Generated by Django 4.1 on 2025-03-17 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_booked_concert_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_concert',
            name='user_name',
            field=models.CharField(default='', max_length=250),
        ),
    ]
