# Generated by Django 4.2.11 on 2026-06-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_concert_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concert_images/'),
        ),
    ]
